services:
  api:
    image: retail-system-api:latest
    ports:
      - "8000:8000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  dashboard:
    image: retail-system-dashboard:latest
    ports:
      - "5173:5173"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
